import SessionProvider from "@/app/providers/SessionProviders";
import Nav from "@/components/Nav";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <SessionProvider>
          <div>
            <Nav />
          </div>
          <div>
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}

